[package]
name = "minesweeper"
version = "1.0.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
rand = "0.9.2"

[build-dependencies]
winres = "0.1.12"

[profile.release]
lto = true
strip = true

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
